# Example configuration file for Hercule RL framework

# List of Gymnasium environments to test
# Can be either simple names (strings) or configurations with hyperparameters
environments:
  # Simple environment names (no hyperparameters)
  - "CartPole-v1"
  - "Acrobot-v1"
  
  # Environment with configuration and hyperparameters
  - name: "FrozenLake-v1"
    hyperparameters:
      - key: "map_name"
        value: "4x4"
      - key: "is_slippery"
        value: false
      - key: "render_mode"
        value: "rgb_array"
  
  # Another environment with different hyperparameters and list values
  - name: "MountainCar-v0"
    hyperparameters:
      - key: "goal_position"
        value: 0.45
      - key: "goal_velocity"
        value: 0.0

# List of models to test with their configurations
models:
  - name: "baseline"
    hyperparameters:
      - key: "num_episodes"
        value: 100
  
  - name: "dqn"
    hyperparameters:
      - key: "learning_rate"
        value: 0.001
      - key: "epsilon"
        value: 0.1
      - key: "batch_size"
        value: 32
      - key: "memory_size"
        value: 10000
  
  - name: "ppo"
    hyperparameters:
      - key: "learning_rate"
        value: 0.0003
      - key: "clip_ratio"
        value: 0.2
      - key: "entropy_coef"
        value: 0.01
      - key: "hidden_layers"
        value: [64, 64]  # List of integers
      - key: "activation_functions"
        value: ["relu", "tanh"]  # List of strings
      - key: "use_layer_norm"
        value: [true, false]  # List of booleans

# Maximum number of training iterations
max_iterations: 1000

# Output directory for results and models
output_dir: "outputs"
